#coding=utf-8
#django command import
from django.core.management.base import BaseCommand
from reports.models import *


class Command(BaseCommand):
    def handle(self, *args, **options):
        #nodes
        node=Node(nb=0,abbr='sum',name='SUM')
        node.save()
        node=Node(nb=1,abbr='bjcst',name='主节点')
        node.save()
        node=Node(nb=2,abbr='senetnod',name='瑞典')
        node.save()
        node=Node(nb=4,abbr='cdtel',name='成都电信')
        node.save()
        node=Node(nb=5,abbr='gzmob',name='广州移动')
        node.save()
        node=Node(nb=6,abbr='krkisa',name='韩国')
        node.save()
        node=Node(nb=7,abbr='denic',name='德国')
        node.save()
        node=Node(nb=8,abbr='usneus',name='美国Neustar')
        node.save()
        node=Node(nb=9,abbr='hkcuhk',name='香港')
        node.save()
        node=Node(nb=10,abbr='usisc',name='美国ISC')
        node.save()
        node=Node(nb=11,abbr='gztel',name='广州电信')
        node.save()
        node=Node(nb=12,abbr='uktata',name='英国')
        node.save()
        node=Node(nb=13,abbr='xatel',name='西安电信')
        node.save()
        node=Node(nb=14,abbr='njuni',name='南京联通')
        node.save()
        node=Node(nb=15,abbr='gzuni',name='广州联通')
        node.save()
        node=Node(nb=16,abbr='njtel',name='南京电信')
        node.save()
        node=Node(nb=17,abbr='jnuni',name='济南联通')
        node.save()
        node=Node(nb=18,abbr='syuni',name='沈阳联通')
        node.save()
        node=Node(nb=19,abbr='bjmob',name='北京移动')
        node.save()
        node=Node(nb=20,abbr='shtel',name='上海电信')
        node.save()
        node=Node(nb=21,abbr='hzal',name='杭州阿里')
        node.save()
        node=Node(nb=24,abbr='bjcgw',name='长城网')
        node.save()
        node=Node(nb=25,abbr='ukman',name='曼彻斯特')
        node.save()
        node=Node(nb=26,abbr='sgtata',name='新加坡')
        node.save()
        node=Node(nb=27,abbr='useqix',name='芝加哥')
        node.save()
        node=Node(nb=29,abbr='nlotdeasynet',name='荷兰')
        node.save()
        node=Node(nb=30,abbr='bjbtc',name='北京联通')
        node.save()
        node=Node(nb=31,abbr='usncc',name='美国达拉斯')
        node.save()
    
    
